In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [4]:
arr1 = np.array([10, 20, 5, 30, 15])
mask = arr > 15
filtered = arr1[arr1 > 15]
print(filtered)

[20 30]


In [5]:
data = np.array([[1,2,3], [4,5,6]])

print(data.mean(axis=1))
print(data.mean(axis=0))

[2. 5.]
[2.5 3.5 4.5]


In [6]:
results = np.where(arr1 > 15,1,0)
print(results)

[0 1 0 1 0]


In [7]:
results2 = np.where(arr1 > 15,0,1)
print(results2)

[1 0 1 0 1]
