In [1]:
import numpy as np

In [3]:
OneD_array = np.array([1,2,3])
TwoD_array = np.array([[1,2,3],[4,5,6]])

print(OneD_array.shape)
print(TwoD_array.shape)

(3,)
(2, 3)


In [4]:
OneD_array2 = ([2,3,4])
print(OneD_array + OneD_array2)
print(OneD_array * OneD_array2)
print(OneD_array * 2)

[3 5 7]
[ 2  6 12]
[2 4 6]


In [5]:
arr1 = np.array([1,2,3,4,5,6])

print(f"Before converting to 2D: {arr1}")

arr2 = arr1.reshape(3,2)

print(f"After converting to 2D: {arr2}")

Before converting to 2D: [1 2 3 4 5 6]
After converting to 2D: [[1 2]
 [3 4]
 [5 6]]


In [6]:
arr = np.array([1,2,3,4])

print(arr.sum())
print(arr.mean())
print(arr.max())

10
2.5
4
